---
# tasks file for roles/bitwarden
- name: Ensure bitwarden-cli is installed
  community.general.homebrew:
    name: bitwarden-cli
    state: present
  tags:
    - bitwarden

- block:
    - name: Check bw config server value
      ansible.builtin.command: "bw config server"
      environment:
        PATH: "{{ ansible_facts.env.PATH }}:{{ additional_path }}"
      changed_when: false
      register: check_bw_config_server
      tags:
        - bitwarden

    - name: Ensure bw config server is set
      ansible.builtin.command: "bw config server {{ bitwarden.server }}"
      environment:
        PATH: "{{ ansible_facts.env.PATH }}:{{ additional_path }}"
      when: "bitwarden.server != check_bw_config_server.stdout"
      tags:
        - bitwarden

- block:
    - name: Check bw login status
      ansible.builtin.command: "bw login --check"
      environment:
        PATH: "{{ ansible_facts.env.PATH }}:{{ additional_path }}"
      failed_when: false
      changed_when: false
      register: check_bw_login
      tags:
        - bitwarden

    - name: Input Two step login code
      ansible.builtin.pause:
        prompt: "? Two-step login code"
      register: two_step_login_code
      when: "'You are logged in!' not in check_bw_login.stdout"
      tags:
        - bitwarden

    - name: Ensure logged into bw
      ansible.builtin.command: "bw login {{ bitwarden.email_address }} {{ bitwarden.password }} --code {{ two_step_login_code.user_input }}"
      environment:
        PATH: "{{ ansible_facts.env.PATH }}:{{ additional_path }}"
      when: "'You are logged in!' not in check_bw_login.stdout"
      tags:
        - bitwarden
