---
- name: Provisioning
  hosts: develop_ubuntu
  roles:
    - apt
    - markosamuli.linuxbrew
    - brew
    - bitwarden
    - gh
  vars:
    # linuxbrew_use_installer: true
    linuxbrew_init_shell: false
  tags: develop_ubuntu

- name: Ensure that deployed config file
  hosts: develop_ubuntu
  tasks:
    - name: Clone config repogitory
      ansible.builtin.git:
        repo: https://github.com/Romira915/romira-s-config.git
        dest: ~/.config/romira-s-config
        update: true
      tags:
        - develop_configuration

    - name: Create symbolic links
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: true
      loop: "{{ develop_configuration.symbolic_links }}"
      tags:
        - develop_configuration

    - name: Ensure that ssh private key is exists
      ansible.builtin.command:
        argv:
          - bw
          - get
          - attachment
          - "{{ develop_configuration.bw_ssh_private_key_attachment_name }}"
          - --itemid
          - "{{ develop_configuration.bw_ssh_private_key_item_id }}"
          - --output
          - "~/.ssh/{{ develop_configuration.bw_ssh_private_key_attachment_name }}"
      args:
        stdin: "{{ bitwarden.password }}"
      tags:
        - develop_configuration

  tags: develop_ubuntu
