---
- name: Provisioning
  hosts: homeservers
  roles:
    - apt
    - iptables
    - user
    - samba
    - wireguard
    - MySQL
    - redis
    - OpenLiteSpeed
    - Nextcloud
    - cron
    - docker
  tags: homeservers
