---
# tasks file for roles/gh
- name: Ensure gh package is installed
  community.windows.win_scoop:
    name: gh
  tags:
    - scoop

- name: Clone github repo
  ansible.windows.win_shell: >-
    GH_TOKEN = '{{ gh.github_fine_grained_token }}';
    gh repo clone {{ item.repo }} {{ item.dest }}
  failed_when: "'already exists' not in gh_repo_clone.stderr and gh_repo_clone.rc != 0"
  changed_when: gh_repo_clone.rc == 0
  register: gh_repo_clone
  loop: "{{ gh.repository }}"
  tags:
    - gh
    - configuration
